
pipeline:
  install: 
   image: node:latest
   commands:
     - npm install
     - npm run lint
     - npm run test
     - npm run build
     - pwd
     - ls
  deploy-test:
    image: plugins/s3-sync:1
    pull: true
    secrets: [aws_access_key_id, aws_secret_access_key]
    bucket: there-be-observables-test
    source: ./dist
    target: builds/${DRONE_PULL_REQUEST}
    region: eu-west-2
    when:
      event: pull_request