
pipeline:
  install: 
   image: node:8.10
   pull: true
   commands:
     - npm install
     - npm run lint
     - npm run test
     - node -v
     - npm run build
     - ls
  deploy-test:
    image: plugins/s3-sync:1
    pull: true
    secrets: [aws_access_key_id, aws_secret_access_key]
    bucket: there-be-observables-test
    source: ./dist
    target: builds/${DRONE_PULL_REQUEST}
    region: eu-west-2
    when:
      event: pull_request