
pipeline:
  install: 
   image: node:latest
   pull: true
   commands:
     - npm install
     - npm run lint
     - npm run test
  deploy-test:
    image: plugins/s3
    pull: true
    settings:
      bucket: there-be-observables-test
      secrets: [aws_access_key, aws_secret_key]
      source: dist/**/*
      target: /${DRONE_PULL_REQUEST}/
    when:
      branch: master
      event: pull_request