
pipeline:
  install: 
   image: node:latest
   pull: true
   commands:
     - npm install
     - npm run lint
     - npm run test
  deploy-test:
    image: plugins/s3
    pull: true
    secrets: [aws_access_key_id, aws_secret_access_key]
    bucket: there-be-observables-test
    region: eu-west-2
    settings:
      source: dist/**/*
      target: /${DRONE_PULL_REQUEST}/location
    when:
      event: pull_request