
pipeline:
  install: 
   image: node:latest
   pull: true
   commands:
     - npm install
     - npm run lint
     - npm run test
  deploy-test:
    image: plugins/s3
    pull: true
    settings:
      bucket: there-be-observables-test
      access_key:
        from_secret: aws_access_key_id
      secret_key:
        from_secret: aws_secret_access_key
      source: dist/**/*
      target: /${DRONE_PULL_REQUEST}/
      region: 'eu-west-2'
