
pipeline:
  install:
    image: node:latest
    pull: true
    commands:
      - node -v
      - npm -v
      - npm install
  test: 
   image: node:latest
   commands:
      - npm run lint
      - npm run test
  build:
    image: node:latest
    commands:
      - npm run build
      - ls dist
  deploy-test:
    image: plugins/s3-sync:1
    pull: true
    secrets: [aws_access_key_id, aws_secret_access_key]
    bucket: there-be-observables-test
    source: ./dist
    target: builds/${DRONE_PULL_REQUEST}
    region: eu-west-2
    when:
      event: pull_request
  deploy-production:
    image: plugins/s3-sync:1
    pull: true
    secrets: [aws_access_key_id, aws_secret_access_key]
    bucket: there-be-observables-prod
    source: ./dist
    region: eu-west-2
    when:
      event: push
      branch: master